import re
import cv2
import numpy as np
import scipy.fft
from typing import List, Dict, Tuple, Any, Optional
from ..schemas import Finding, LayerOutput, BoundingBox

try:
    import pymupdf as fitz
except ImportError:
    import fitz

AI_GENERATOR_KEYWORDS = [
    "midjourney", "dall-e", "dalle", "stable diffusion", "stablediffusion",
    "flux.1", "ideogram", "leonardo.ai", "firefly", "adobe firefly",
    "canva magic", "chatgpt", "openai", "anthropic", "claude",
    "copilot", "bing image creator", "synthesia", "craiyon", "runwayml",
    "deepfloyd", "imagen", "generative ai", "synthetically generated"
]

def detect_ai_metadata_signatures(raw_metadata: Dict[str, Any], file_bytes: bytes) -> List[str]:
    """Scans container metadata, XMP streams, and raw bytes for AI generator tags."""
    detected_markers = []
    
    # 1. Structured metadata inspection
    for key, val in raw_metadata.items():
        if isinstance(val, str):
            val_lower = val.lower()
            for kw in AI_GENERATOR_KEYWORDS:
                if kw in val_lower and kw not in detected_markers:
                    detected_markers.append(f"Metadata '{key}' contains generative AI signature: '{val}'")

    # 2. Raw binary byte scan for XMP generative tags
    try:
        raw_text_sample = file_bytes[:100000].decode("utf-8", errors="ignore").lower()
        if "photoshop:generative" in raw_text_sample or "generativeai" in raw_text_sample:
            detected_markers.append("Embedded XMP stream contains Adobe Firefly / Generative AI fill tag")
        if "prompt" in raw_text_sample and ("dall-e" in raw_text_sample or "midjourney" in raw_text_sample):
            detected_markers.append("Embedded generation prompt discovered in container metadata")
    except Exception:
        pass

    return detected_markers


def detect_spectral_diffusion_grid(img_cv: np.ndarray) -> Tuple[bool, float, float]:
    """
    Analyzes 2D Discrete Cosine Transform (DCT) / Fourier spectrum to detect
    periodic grid artifacts characteristic of transposed convolution in Latent Diffusion Models.
    Returns:
        (is_ai_spectral_anomaly, high_freq_ratio, spectral_variance)
    """
    try:
        gray = cv2.cvtColor(img_cv, cv2.COLOR_BGR2GRAY) if len(img_cv.shape) == 3 else img_cv
        h, w = gray.shape[:2]
        
        # Resize to standard 512x512 for consistent frequency analysis
        resized = cv2.resize(gray, (512, 512)).astype(np.float32)
        
        # 2D Orthogonal DCT
        dct = scipy.fft.dctn(resized, norm='ortho')
        abs_dct = np.abs(dct)
        
        # High-frequency corner energy ratio
        total_energy = np.sum(abs_dct) + 1e-6
        high_freq_corner = abs_dct[256:, 256:]
        high_energy = np.sum(high_freq_corner)
        high_ratio = float(high_energy / total_energy) * 100.0
        
        # Check for unnatural periodic spikes in frequency domain (checkerboard artifacts)
        # Real camera scans and vector documents have power decay 1/f; synthetic upsamplers exhibit abnormal grid peaks
        mid_high_band = abs_dct[128:384, 128:384]
        spectral_var = float(np.var(mid_high_band))
        
        is_synthetic = (high_ratio > 18.5) and (spectral_var > 450.0)
        return is_synthetic, round(high_ratio, 2), round(spectral_var, 2)
    except Exception as e:
        print("Spectral AI analysis warning:", e)
        return False, 0.0, 0.0


def scan_for_synthetic_watermarks_and_tokens(text: str) -> List[str]:
    """Scans text for zero-width space watermarks and synthetic LLM repetition patterns."""
    reasons = []
    
    # Zero-width spaces often used for AI generation watermarking
    zw_chars = ["\u200b", "\u200c", "\u200d", "\ufeff"]
    zw_count = sum(text.count(c) for c in zw_chars)
    if zw_count > 4:
        reasons.append(f"Concealed zero-width steganographic watermarks detected ({zw_count} characters)")

    # Common LLM hallucinated document boilerplate
    llm_boilerplate = [
        "as an ai language model",
        "sample generated document",
        "lorem ipsum dolor sit amet",
        "generated by openai",
        "this invoice is for demonstration purposes only"
    ]
    t_lower = text.lower()
    for bp in llm_boilerplate:
        if bp in t_lower:
            reasons.append(f"Synthetic LLM boilerplate string detected: '{bp}'")

    return reasons


def analyze_ai_generation(
    file_bytes: bytes,
    filename: str,
    raw_metadata: Dict[str, Any],
    primary_img_cv: np.ndarray,
    full_text: str = ""
) -> Tuple[LayerOutput, List[Finding]]:
    """
    Dedicated AI Generation and Synthetic Document Verification Engine.
    Combines:
    1. Container & XMP generative AI tool signatures
    2. 2D DCT spectral lattice and checkerboard upsampling artifacts
    3. Synthetic zero-width token watermarking
    4. 100% full-page rasterized document trapping
    """
    findings: List[Finding] = []
    overlay_boxes: List[BoundingBox] = []
    
    # 1. Metadata signatures
    meta_markers = detect_ai_metadata_signatures(raw_metadata, file_bytes)
    
    # 2. Spectral diffusion grid check
    is_spectral_synth, high_ratio, spec_var = detect_spectral_diffusion_grid(primary_img_cv)
    
    # 3. Watermark / LLM token scan
    text_synth_markers = scan_for_synthetic_watermarks_and_tokens(full_text)

    # 4. Check for full-page raster masquerading as PDF with no fonts
    is_pdf = filename.lower().endswith(".pdf")
    is_flat_raster_pdf = False
    if is_pdf:
        try:
            doc = fitz.open(stream=file_bytes, filetype="pdf")
            if len(doc) >= 1:
                page = doc[0]
                text_len = len(page.get_text().strip())
                image_list = page.get_images()
                # If page has 0 digital vector text but 1 massive image filling the entire page
                if text_len == 0 and len(image_list) >= 1:
                    is_flat_raster_pdf = True
            doc.close()
        except Exception:
            pass

    all_ai_reasons = []
    all_ai_reasons.extend(meta_markers)
    all_ai_reasons.extend(text_synth_markers)

    if is_spectral_synth:
        all_ai_reasons.append(f"High-frequency 2D DCT spectral lattice artifact detected (Energy: {high_ratio}%, Var: {spec_var})")

    flagged = len(all_ai_reasons) > 0
    score = 100

    if flagged:
        score = max(15, 100 - (len(all_ai_reasons) * 35))
        severity = "Critical" if (meta_markers or text_synth_markers) else "High"
        
        # Add visual bounding box spanning synthetic document header or central area
        box = BoundingBox(
            id="box-ai-gen-0",
            page=1,
            x=5.0,
            y=5.0,
            width=90.0,
            height=90.0,
            label="Synthetic AI Generation Signature",
            layer_type="ai_generation",
            tag="AI-GENERATED",
            color="#8B5CF6",
            target_finding_id="finding-ai-gen"
        )
        overlay_boxes.append(box)

        findings.append(Finding(
            id="finding-ai-gen",
            layer_type="ai_generation",
            severity=severity,
            title="Synthetic AI Document Generation Detected",
            description=f"Document exhibits multiple signatures of generative AI creation: {'; '.join(all_ai_reasons)}.",
            confidence=0.96,
            bounding_boxes=overlay_boxes,
            details={
                "ai_markers": all_ai_reasons,
                "high_frequency_ratio": f"{high_ratio}%",
                "spectral_variance": spec_var,
                "flat_raster_pdf": is_flat_raster_pdf
            }
        ))

    layer_output = LayerOutput(
        layer_id="ai_generation",
        name="AI Generation & Synthetic Check",
        description="Detects Midjourney/DALL-E image synthesis, LLM watermarks, and diffusion lattice artifacts",
        score=score,
        flagged=flagged,
        findings_count=len(findings),
        overlay_items=overlay_boxes
    )

    return layer_output, findings
